### ISSUE TITLE
lingua 4.10 fails with Python3 due to non-existing unicode() function

### ISSUE THREAD

**Issue by omarkohl** [wichert/lingua#82]
In lingua 4.10 we find the new line `output.write(unicode(catalog))` . This is not valid Python3 because the global `unicode()` function has been removed.

```
Traceback (most recent call last):
  File ".../bin/pot-create", line 11, in <module>
    sys.exit(main())
  File ".../lib/python3.4/site-packages/lingua/extract.py", line 359, in main
    save_catalog(catalog, options.output)
  File ".../lib/python3.4/site-packages/lingua/extract.py", line 236, in save_catalog
    output.write(unicode(catalog))
NameError: name 'unicode' is not defined
```

**Comment by omarkohl** [comment]
Wow that was quick! Thanks!
